# See more options from https://alacritty.org/config-alacritty.html

[font]
size = 14.0

[font.normal]
family = "Maple Mono NF"
style = "Regular"

[scrolling]
multiplier = 3

[selection]
save_to_clipboard = true

[window]
dynamic_padding = true
#decorations = "Buttonless"

[window.padding]
x = 3
y = 3
